clc;clear;
A = [1 3 3 2;2 6 9 7;-1 -3 3 4];
disp('A=',A);
[m,n]=size(A);
disp('m=',m);
disp('n=',n);
[v,pivot]=rref(A);
disp(rref(A));
disp(v);
r=length(pivot);
disp('rank=',r);
cs=A(:,pivot);
disp('Column Space=',cs);
ns=kernel(A);
disp('Null Space',ns);
rs=v(1:r,:)';
disp('Row Space=',rs);
lns=kernel(A');
disp('Left Null Space=',lns);
